import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Navbar from "@/Components/navbar";
import Footer from "@/Components/footer";
import "./globals.css";
import QueryProvider from "@/Providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <Toaster position="top-center" />

        <div className="min-h-screen bg-slate-900 text-white relative overflow-hidden">
          <div className="absolute inset-0 overflow-hidden z-0">
            <div className="absolute inset-0 bg-gradient-to-br from-indigo-900 via-purple-900 to-slate-900 opacity-80"></div>

            <div className="absolute -top-20 -left-20 w-96 h-96 rounded-full bg-blue-500 opacity-10 blur-3xl"></div>
            <div className="absolute top-1/3 right-10 w-80 h-80 rounded-full bg-purple-600 opacity-10 blur-3xl"></div>
            <div className="absolute bottom-20 left-1/4 w-72 h-72 rounded-full bg-indigo-400 opacity-10 blur-3xl"></div>
            <div className="absolute top-3/4 right-1/3 w-64 h-64 rounded-full bg-violet-500 opacity-15 blur-3xl"></div>

            <div className="absolute top-0 left-0 w-full h-px bg-gradient-to-r from-transparent via-purple-500 to-transparent opacity-20"></div>
            <div className="absolute bottom-0 left-0 w-full h-px bg-gradient-to-r from-transparent via-blue-500 to-transparent opacity-20"></div>
          </div>

          <div className="absolute inset-0 bg-grid-pattern opacity-5 pointer-events-none z-0"></div>

          {/* Content Layer */}
          <div className="relative z-10">
            <div className="px-6 md:px-12 lg:px-16 xl:px-24">
              <Navbar />
            </div>
            <QueryProvider>{children}</QueryProvider>

            <div className="px-6 md:px-12 lg:px-16 xl:px-24">
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
